include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/amplifyconfiguration.dart"
    - "**/firebase_options.dart"
