name: flutter_core
description: "A flutter package for some basic things."
version: 0.0.6

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
