name: flutter_core
description: "A new Flutter package project."
version: 0.0.3

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
